// direct-mode/clients/web/reference/vue/src/components/ControlPanel.vue
<script setup lang="ts">
import { pushToast } from '../composables/useToast'
import { ref, computed, watch } from 'vue'
import type { AvatarController } from '@spatius/avatarkit'
import type { AvatarInstance } from '../composables/useAvatarSDK'
import { PCM_ASSETS, AUDIO_SOURCE_HINT } from '../data/audioAssets'
import { loadPcmFile, sendPcmChunks } from '../utils/audio'

interface AvatarSlot {
  uid: string
  index: number
  name: string
}

const props = defineProps<{
  activeAvatar: AvatarInstance | null
  activeController: AvatarController | null
  multiMode?: boolean
  avatarSlots?: AvatarSlot[]
  activeUid?: string | null
}>()

const emit = defineEmits<{
  slotSelect: [uid: string]
}>()

// Track which clip is playing, not just that one is: swapping every button's
// label at once resizes them and reflows the panel, which stutters the canvas.
const sendingPath = ref<string | null>(null)
const sending = computed(() => sendingPath.value !== null)
const sdkCancelRef = ref<(() => void) | null>(null)

const connected = computed(() => props.activeAvatar?.connectionState === 'connected')
const hasAvatar = computed(() => props.activeAvatar?.view !== null && !props.activeAvatar?.loading)

async function handleStart() {
  if (!props.activeController) return
  try {
    await (props.activeController as any).initializeAudioContext()
    await props.activeController.start()
  } catch (e: any) {
    console.error('Start failed:', e)
    pushToast(`Failed to connect: ${e?.message ?? e}`)
  }
}

async function handleSendPcm(path: string) {
  // Direct Mode has no session until start() runs, so audio sent now would be
  // dropped silently. Say so instead of leaving a dead button.
  if (!connected.value) {
    pushToast('Please click Start to connect before sending audio.', 'warning')
    return
  }
  if (!props.activeController || sending.value) return
  sendingPath.value = path
  try {
    // The audio context is already warmed up by handleStart.
    const data = await loadPcmFile(path)
    sdkCancelRef.value = sendPcmChunks(
      data,
      (chunk, end) => props.activeController!.send(chunk.buffer as ArrayBuffer, end),
      () => { sendingPath.value = null },
    )
  } catch (e: any) {
    console.error('Send failed:', e)
    pushToast(`Failed to send audio: ${e?.message ?? e}`)
    sendingPath.value = null
  }
}

function handlePause() { props.activeController?.pause() }
function handleResume() { props.activeController?.resume() }
function handleInterrupt() {
  props.activeController?.interrupt()
  if (sdkCancelRef.value) { sdkCancelRef.value(); sdkCancelRef.value = null }
  sendingPath.value = null
}

// Cancel ongoing audio send when disconnected
watch(connected, (val) => {
  if (!val && sdkCancelRef.value) {
    sdkCancelRef.value()
    sdkCancelRef.value = null
    sendingPath.value = null
  }
})
</script>

<template>
  <div class="control-panel">
    <h3>Controls</h3>
    <!-- Status -->
    <div v-if="activeAvatar" class="status-bar">
      <div class="status-row">
        <span class="status-label">Connection</span>
        <span :class="['status-value', activeAvatar.connectionState]">
          {{ activeAvatar.connectionState }}
        </span>
      </div>
      <div class="status-row">
        <span class="status-label">Conversation</span>
        <span class="status-value">{{ activeAvatar.conversationState }}</span>
      </div>
      <div v-if="activeAvatar.error" class="status-row error">
        <span class="status-label">Error</span>
        <span class="status-value error-text">{{ activeAvatar.error }}</span>
      </div>
    </div>

    <!-- Slot selector in multi mode -->
    <div v-if="multiMode && avatarSlots && avatarSlots.length > 0" class="slot-selector">
      <h4>Active Avatar</h4>
      <div class="slot-list">
        <button
          v-for="s in avatarSlots"
          :key="s.uid"
          :class="['slot-btn', { active: s.uid === activeUid }]"
          @click="emit('slotSelect', s.uid)"
        >
          <span class="slot-index">{{ s.index }}</span>
          <span class="slot-name">{{ s.name }}</span>
        </button>
      </div>
    </div>

    <p v-if="!hasAvatar" class="panel-hint">Load a character first</p>

    <!-- Direct Mode -->
    <template v-if="hasAvatar">
      <button
        class="primary full-width"
        :disabled="connected || !hasAvatar"
        @click="handleStart"
      >
        {{ connected ? 'Connected' : 'Start' }}
      </button>

      <div class="audio-list">
        <h4>
          Audio Files
          <span class="audio-hint" :title="AUDIO_SOURCE_HINT">?</span>
        </h4>
        <button
          v-for="a in PCM_ASSETS"
          :key="a.path"
          class="secondary full-width audio-btn"
          :disabled="sending"
          @click="handleSendPcm(a.path)"
        >
          {{ sendingPath === a.path ? '...' : `&#9654; ${a.name}` }}
        </button>
      </div>
    </template>

    <!-- Common controls -->
    <div v-if="hasAvatar" class="btn-row">
      <button class="secondary" @click="handlePause">Pause</button>
      <button class="secondary" @click="handleResume">Resume</button>
      <button class="danger" @click="handleInterrupt">Interrupt</button>
    </div>
  </div>
</template>

// direct-mode/clients/web/reference/react/src/components/ControlPanel.tsx
import { useState, useRef, useCallback, useEffect } from 'react'
import type { AvatarController } from '@spatius/avatarkit'
import type { AvatarInstance } from '../hooks/useAvatarSDK'
import { PCM_ASSETS, AUDIO_SOURCE_HINT } from '../data/audioAssets'
import { loadPcmFile, sendPcmChunks } from '../utils/audio'

interface AvatarSlot {
  uid: string
  index: number
  name: string
}

interface Props {
  activeAvatar: AvatarInstance | null
  activeController: AvatarController | null
  multiMode?: boolean
  avatarSlots?: AvatarSlot[]
  activeUid?: string | null
  onSlotSelect?: (uid: string) => void
  onNotify?: (text: string, kind?: 'error' | 'warning') => void
}

export default function ControlPanel({ activeAvatar, activeController, multiMode, avatarSlots, activeUid, onSlotSelect, onNotify }: Props) {
  // Track which clip is playing, not just that one is: swapping every button's
  // label at once resizes them and reflows the panel, which stutters the canvas.
  const [sendingPath, setSendingPath] = useState<string | null>(null)
  const sending = sendingPath !== null
  const sdkCancelRef = useRef<(() => void) | null>(null)

  const connected = activeAvatar?.connectionState === 'connected'
  const hasAvatar = activeAvatar?.view !== null && !activeAvatar?.loading

  const handleStart = useCallback(async () => {
    if (!activeController) return
    try {
      await (activeController as any).initializeAudioContext()
      await activeController.start()
    } catch (e: any) {
      console.error('Start failed:', e)
      onNotify?.(`Failed to connect: ${e?.message ?? e}`)
    }
  }, [activeController, onNotify])

  const handleSendPcm = useCallback(async (path: string) => {
    // Direct Mode has no session until start() runs, so audio sent now would be
    // dropped silently. Say so instead of leaving a dead button.
    if (!connected) {
      onNotify?.('Please click Start to connect before sending audio.', 'warning')
      return
    }
    if (!activeController || sending) return
    setSendingPath(path)
    try {
      // The audio context is already warmed up by handleStart; doing it here
      // again stalls the first frames of playback.
      const data = await loadPcmFile(path)
      sdkCancelRef.current = sendPcmChunks(
        data,
        (chunk, end) => activeController.send(chunk.buffer as ArrayBuffer, end),
        () => setSendingPath(null),
      )
    } catch (e: any) {
      console.error('Send failed:', e)
      onNotify?.(`Failed to send audio: ${e?.message ?? e}`)
      setSendingPath(null)
    }
  }, [activeController, sending, connected, onNotify])

  const handlePause = () => activeController?.pause()
  const handleResume = () => activeController?.resume()
  const handleInterrupt = () => {
    activeController?.interrupt()
    if (sdkCancelRef.current) { sdkCancelRef.current(); sdkCancelRef.current = null }
    setSendingPath(null)
  }

  useEffect(() => {
    if (!connected && sdkCancelRef.current) {
      sdkCancelRef.current()
      sdkCancelRef.current = null
      setSendingPath(null)
    }
  }, [connected])

  return (
    <div className="control-panel">
      <h3>Controls</h3>

      {activeAvatar && (
        <div className="status-bar">
          <div className="status-row">
            <span className="status-label">Connection</span>
            <span className={`status-value ${activeAvatar.connectionState}`}>
              {activeAvatar.connectionState}
            </span>
          </div>
          <div className="status-row">
            <span className="status-label">Conversation</span>
            <span className="status-value">{activeAvatar.conversationState}</span>
          </div>
          {activeAvatar.error && (
            <div className="status-row error">
              <span className="status-label">Error</span>
              <span className="status-value error-text">{activeAvatar.error}</span>
            </div>
          )}
        </div>
      )}

      {multiMode && avatarSlots && avatarSlots.length > 0 && (
        <div className="slot-selector">
          <h4>Active Avatar</h4>
          <div className="slot-list">
            {avatarSlots.map(s => (
              <button
                key={s.uid}
                className={`slot-btn ${s.uid === activeUid ? 'active' : ''}`}
                onClick={() => onSlotSelect?.(s.uid)}
              >
                <span className="slot-index">{s.index}</span>
                <span className="slot-name">{s.name}</span>
              </button>
            ))}
          </div>
        </div>
      )}

      {!hasAvatar && (
        <p className="panel-hint">Load a character first</p>
      )}

      {hasAvatar && (
        <>
          <button
            className="primary full-width"
            disabled={connected || !hasAvatar}
            onClick={handleStart}
          >
            {connected ? 'Connected' : 'Start'}
          </button>

          <div className="audio-list">
            <h4>
              Audio Files
              <span className="audio-hint" title={AUDIO_SOURCE_HINT}>?</span>
            </h4>
            {PCM_ASSETS.map(a => (
              <button
                key={a.path}
                className="secondary full-width audio-btn"
                disabled={sending}
                onClick={() => handleSendPcm(a.path)}
              >
                {sendingPath === a.path ? '...' : `▶ ${a.name}`}
              </button>
            ))}
          </div>

          <div className="btn-row">
            <button className="secondary" onClick={handlePause}>Pause</button>
            <button className="secondary" onClick={handleResume}>Resume</button>
            <button className="danger" onClick={handleInterrupt}>Interrupt</button>
          </div>
        </>
      )}
    </div>
  )
}
