// backend-mode/clients/web/vue/src/App.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { AvatarSDK, DrivingServiceMode, LogLevel } from '@spatius/avatarkit'
import Playground from './views/Playground.vue'
import './App.css'

const ready = ref(false)
const error = ref<string | null>(null)

function deriveHttpBase(): string {
  const wsUrl = import.meta.env.VITE_BACKEND_MODE_WS_URL || 'ws://localhost:8765/ws/agent'
  const httpUrl = wsUrl.replace(/^ws(s?):\/\//, 'http$1://').replace(/\/ws\/agent$/, '')
  return httpUrl
}

onMounted(async () => {
  const httpBase = deriveHttpBase()

  let appId: string
  let region: string | undefined
  try {
    const res = await fetch(`${httpBase}/api/config`)
    if (!res.ok) throw new Error(`Server returned ${res.status}`)
    const config = await res.json()
    appId = config.appId
    region = config.region
    if (!appId) throw new Error('Server returned empty appId')
  } catch (e: any) {
    // Try /healthz to give a more specific error message
    try {
      const healthRes = await fetch(`${httpBase}/healthz`)
      const health = await healthRes.json()
      if (!health.ok && health.missing?.length) {
        error.value = `Server missing config: ${health.missing.join(', ')}`
        return
      }
    } catch {
      // healthz also failed
    }
    error.value = `Failed to fetch config from ${httpBase}/api/config: ${e.message}`
    return
  }

  try {
    await AvatarSDK.initialize(appId, {
      drivingServiceMode: DrivingServiceMode.backend,
      audioFormat: { channelCount: 1, sampleRate: 16000 },
      logLevel: LogLevel.all,
      ...(region ? { region } : {}),
    })
    ready.value = true
  } catch (e: any) {
    error.value = e.message || 'SDK initialization failed'
  }
})
</script>

<template>
  <div class="app">
    <div v-if="error" class="init-error">
      <a href="https://app.spatius.ai" target="_blank" rel="noreferrer">
        <img src="/api-key-guide.png" alt="API Key Guide" style="max-width: 100%; border-radius: 10px; margin-bottom: 16px;" />
      </a>
      <p>{{ error }}</p>
    </div>
    <Playground v-if="ready" />
  </div>
</template>

// backend-mode/clients/web/nextjs-direct/app/page.tsx
'use client'

import { useState, useEffect } from 'react'
import {
  AvatarSDK,
  DrivingServiceMode,
    LogLevel,
} from '@spatius/avatarkit'
import Playground from '@/views/Playground'

export default function Home() {
  const [ready, setReady] = useState(false)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    const wsUrl = process.env.NEXT_PUBLIC_BACKEND_MODE_WS_URL || 'ws://localhost:8765/ws/agent'
    const httpBase = wsUrl.replace(/^ws(s?):\/\//, 'http$1://').replace(/\/ws\/agent$/, '')

    fetch(`${httpBase}/api/config`)
      .then(async (res) => {
        if (!res.ok) throw new Error(`Config endpoint returned ${res.status}`)
        const config = await res.json()
        if (!config.appId) throw new Error('Server returned empty appId')
        return config
      })
      .then((config) =>
        AvatarSDK.initialize(config.appId, {
          region: config.region === 'us-west' ? 'us-west' : 'us-west',
          drivingServiceMode: DrivingServiceMode.backend,
          audioFormat: { channelCount: 1, sampleRate: 16000 },
          logLevel: LogLevel.all,
        })
      )
      .then(() => setReady(true))
      .catch(async (e: any) => {
        // Try /healthz to show which env vars are missing on the server
        try {
          const health = await fetch(`${httpBase}/healthz`).then((r) => r.json())
          if (!health.ok && health.missing?.length) {
            setError(`Server missing config: ${health.missing.join(', ')}`)
            return
          }
        } catch { /* healthz also unavailable */ }
        setError(e.message || 'SDK initialization failed')
      })
  }, [])

  if (error) {
    return (
      <div className="config-error" style={{ padding: 32, textAlign: 'center' }}>
        <a href="https://app.spatius.ai" target="_blank" rel="noreferrer">
          <img src="/api-key-guide.png" alt="API Key Guide" style={{ maxWidth: '100%', borderRadius: 10, marginBottom: 16 }} />
        </a>
        <p>{error}</p>
      </div>
    )
  }

  if (!ready) {
    return <div style={{ textAlign: 'center', padding: '2rem' }}>Initializing SDK...</div>
  }

  return (
    <div className="app">
      <div className="view active">
        <Playground />
      </div>
    </div>
  )
}
