// direct-mode/clients/web/reference/vue/src/views/Configuration.vue
<script setup lang="ts">
import { ref, computed } from 'vue'
import {
  AvatarSDK,
  DrivingServiceMode,
  LogLevel,
} from '@spatius/avatarkit'
import type { AppConfig } from '../App.vue'

const DASH_URL = 'https://app.spatius.ai'
const SUPPORTED_REGIONS = ['us-west', 'ap-northeast', 'cn-beijing'] as const
const STORAGE_KEY = 'avatarkit-playground-config'

const emit = defineEmits<{
  initialized: [config: AppConfig]
}>()

function loadCached() {
  try {
    const raw = localStorage.getItem(STORAGE_KEY)
    if (raw) return JSON.parse(raw) as { appId?: string; token?: string; env?: string }
  } catch { /* ignore */ }
  return {}
}

function saveCache(appId: string, token: string, env: string) {
  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify({ appId, token, env }))
  } catch { /* ignore */ }
}

function normalizeRegion(env?: string) {
  return env && SUPPORTED_REGIONS.includes(env as (typeof SUPPORTED_REGIONS)[number]) ? env : 'us-west'
}

const cached = loadCached()
const appId = ref(cached.appId ?? '')
const token = ref(cached.token ?? '')
const env = ref<string>(normalizeRegion(cached.env))
const loading = ref(false)
const error = ref<string | null>(null)

const canInit = computed(() => appId.value.trim() && token.value.trim())

async function handleInit() {
  if (!canInit.value) return
  loading.value = true
  error.value = null
  try {
    await AvatarSDK.initialize(appId.value.trim(), {
      region: env.value,
      drivingServiceMode: DrivingServiceMode.direct,
      audioFormat: { channelCount: 1, sampleRate: 16000 },
      logLevel: LogLevel.all,
    })
    AvatarSDK.setSessionToken(token.value.trim())
    saveCache(appId.value.trim(), token.value.trim(), env.value)
    emit('initialized', {
      appId: appId.value.trim(),
      sessionToken: token.value.trim(),
      region: env.value,
    })
  } catch (e: any) {
    error.value = e.message || 'Initialization failed'
  } finally {
    loading.value = false
  }
}
</script>

<template>
  <div class="config-view">
    <div class="config-layout">
      <div class="config-container">
        <h1>Configuration</h1>
        <p class="config-subtitle">
          Mode: <strong>Direct Mode</strong>
        </p>
        <div class="config-form">
          <div class="field">
            <label>App ID <span class="required">*</span></label>
            <input
              v-model="appId"
              placeholder="app_xxx"
            />
            <span class="field-hint">
              Get your App ID from the
              <a :href="DASH_URL" target="_blank" rel="noreferrer">Developer Platform</a>
            </span>
          </div>

          <div class="field">
            <label>Session Token <span class="required">*</span></label>
            <input
              type="password"
              v-model="token"
              placeholder="Your session token"
            />
            <span class="field-hint">
              Required for server communication in Direct Mode
            </span>
          </div>

          <div class="field">
            <label>Region</label>
            <select v-model="env">
              <option v-for="region in SUPPORTED_REGIONS" :key="region" :value="region">
                {{ region }}
              </option>
            </select>
          </div>

          <div v-if="error" class="config-error">{{ error }}</div>

          <button
            class="primary init-btn"
            :disabled="!canInit || loading"
            @click="handleInit"
          >
            {{ loading ? 'Initializing...' : 'Initialize SDK' }}
          </button>
        </div>
      </div>
      <a class="config-guide" :href="DASH_URL" target="_blank" rel="noreferrer">
        <img src="/api-key-guide.png" alt="Where to find your App ID and Token" />
      </a>
    </div>
  </div>
</template>

// direct-mode/clients/web/reference/react/src/views/Configuration.tsx
import { useState } from 'react'
import {
  AvatarSDK,
  DrivingServiceMode,
  LogLevel,
} from '@spatius/avatarkit'
import type { AppConfig } from '../App'

const DASH_URL = 'https://app.spatius.ai'
const SUPPORTED_REGIONS = ['us-west', 'ap-northeast', 'cn-beijing'] as const

interface Props {
  mode: DrivingServiceMode
  onInitialized: (config: AppConfig) => void
}

const STORAGE_KEY = 'avatarkit-playground-config'

function loadCached() {
  try {
    const raw = localStorage.getItem(STORAGE_KEY)
    if (raw) return JSON.parse(raw) as { appId?: string; token?: string; env?: string }
  } catch { /* ignore */ }
  return {}
}

function saveCache(appId: string, token: string, env: string) {
  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify({ appId, token, env }))
  } catch { /* ignore */ }
}

function normalizeRegion(env?: string) {
  return env && SUPPORTED_REGIONS.includes(env as (typeof SUPPORTED_REGIONS)[number]) ? env : 'us-west'
}

export default function Configuration({ mode, onInitialized }: Props) {
  const cached = loadCached()
  const [appId, setAppId] = useState(cached.appId ?? '')
  const [token, setToken] = useState(cached.token ?? '')
  const [env, setEnv] = useState<string>(normalizeRegion(cached.env))
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)

  const canInit = appId.trim() && token.trim()

  const handleInit = async () => {
    if (!canInit) return
    setLoading(true)
    setError(null)
    try {
      await AvatarSDK.initialize(appId.trim(), {
        region: env,
        drivingServiceMode: mode,
        audioFormat: { channelCount: 1, sampleRate: 16000 },
        logLevel: LogLevel.all,
      })
      AvatarSDK.setSessionToken(token.trim())
      saveCache(appId.trim(), token.trim(), env)
      onInitialized({ appId: appId.trim(), sessionToken: token.trim(), region: env })
    } catch (e: any) {
      setError(e.message || 'Initialization failed')
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="config-view">
      <div className="config-layout">
        <div className="config-container">
          <h1>AvatarKit Direct Mode Demo</h1>
          <p className="config-subtitle">
            Send pre-recorded audio to the avatar and see lip-sync in action.
          </p>

          <div className="config-form">
            <div className="field">
              <label>App ID <span className="required">*</span></label>
              <input
                value={appId}
                onChange={e => setAppId(e.target.value)}
                placeholder="app_xxx"
              />
              <span className="field-hint">
                Get your App ID from the{' '}
                <a href={DASH_URL} target="_blank" rel="noreferrer">
                  Developer Platform
                </a>
              </span>
            </div>

            <div className="field">
              <label>Session Token <span className="required">*</span></label>
              <input
                type="password"
                value={token}
                onChange={e => setToken(e.target.value)}
                placeholder="Your session token"
              />
              <span className="field-hint">
                Required for server communication in Direct Mode
              </span>
            </div>

            <div className="field">
              <label>Region</label>
              <select value={env} onChange={e => setEnv(e.target.value as string)}>
                {SUPPORTED_REGIONS.map(region => (
                  <option key={region} value={region}>{region}</option>
                ))}
              </select>
            </div>

            {error && <div className="config-error">{error}</div>}

            <button
              className="primary init-btn"
              disabled={!canInit || loading}
              onClick={handleInit}
            >
              {loading ? 'Initializing...' : 'Initialize SDK'}
            </button>
          </div>
        </div>

        <a className="config-guide" href={DASH_URL} target="_blank" rel="noreferrer">
          <img src="/api-key-guide.png" alt="Where to find your App ID and Token" />
        </a>
      </div>
    </div>
  )
}
