// direct-mode/clients/web/reference/react/src/App.tsx
import { useState, useCallback } from 'react'
import { DrivingServiceMode } from '@spatius/avatarkit'
import Configuration from './views/Configuration'
import Playground from './views/Playground'
import './App.css'

export interface AppConfig {
  appId: string
  sessionToken: string
  region: string
}

const MODE = DrivingServiceMode.direct

export default function App() {
  const [step, setStep] = useState<1 | 2>(1)
  const [config, setConfig] = useState<AppConfig | null>(null)

  const handleInitialized = useCallback((c: AppConfig) => {
    setConfig(c)
    setStep(2)
  }, [])

  return (
    <div className="app">
      <div className={`view ${step === 1 ? 'active' : ''}`}>
        <Configuration
          mode={MODE}
          onInitialized={handleInitialized}
        />
      </div>
      <div className={`view ${step === 2 ? 'active' : ''}`}>
        {config && step === 2 && (
          <Playground mode={MODE} config={config} />
        )}
      </div>
    </div>
  )
}

// direct-mode/clients/web/reference/vue/src/App.vue
<script setup lang="ts">
import { ref } from 'vue'
import Configuration from './views/Configuration.vue'
import Playground from './views/Playground.vue'
import './App.css'

export interface AppConfig {
  appId: string
  sessionToken: string
  region: string
}

const step = ref<1 | 2>(1)
const config = ref<AppConfig | null>(null)

function handleInitialized(c: AppConfig) {
  config.value = c
  step.value = 2
}
</script>

<template>
  <div class="app">
    <div :class="['view', { active: step === 1 }]">
      <Configuration
        @initialized="handleInitialized"
      />
    </div>
    <div :class="['view', { active: step === 2 }]">
      <Playground
        v-if="config && step === 2"
        :config="config"
      />
    </div>
  </div>
</template>
