// direct-mode/clients/web/reference/vue/src/components/CharacterList.vue
<script setup lang="ts">
import { ref } from 'vue'
import { DEFAULT_CHARACTERS } from '../data/characters'

const DASH_URL = 'https://app.spatius.ai'

interface Character {
  id: string
  name: string
}

defineProps<{
  loadingId: string | null
  loadProgress: number
}>()

const emit = defineEmits<{
  select: [id: string, name: string]
}>()

const adding = ref(false)
const customId = ref('')
const customChars = ref<Character[]>([])

function handleAdd() {
  const id = customId.value.trim()
  if (!id) return
  if ([...DEFAULT_CHARACTERS, ...customChars.value].some(c => c.id === id)) return
  const name = `Custom (${id.slice(0, 6)}...)`
  customChars.value = [...customChars.value, { id, name }]
  customId.value = ''
  adding.value = false
}

const allChars = () => [...DEFAULT_CHARACTERS, ...customChars.value]
</script>

<template>
  <div class="character-list">
    <h3>Characters</h3>
    <div class="character-items">
      <button
        v-for="c in allChars()"
        :key="c.id"
        :class="['character-item', { loading: loadingId === c.id }]"
        :disabled="loadingId !== null"
        @click="emit('select', c.id, c.name)"
      >
        <span class="character-avatar">{{ c.name.charAt(0) }}</span>
        <span class="character-name">{{ c.name }}</span>
        <span v-if="loadingId === c.id" class="character-progress">{{ Math.round(loadProgress * 100) }}%</span>
      </button>
      <div v-if="adding" class="custom-id-input">
        <input
          v-model="customId"
          @keydown.enter="handleAdd"
          placeholder="Paste character ID"
          autofocus
        />
        <div class="custom-id-actions">
          <button class="primary" :disabled="!customId.trim() || loadingId !== null" @click="handleAdd">Add</button>
          <button class="secondary" @click="adding = false; customId = ''">Cancel</button>
        </div>
      </div>
      <button v-else class="character-item add-btn" @click="adding = true">
        <span class="character-avatar add-avatar">+</span>
        <span class="character-name">Custom ID</span>
      </button>
    </div>

    <a class="guide-thumb list-guide" :href="DASH_URL" target="_blank" rel="noreferrer">
      <img src="/public-avatar-guide.png" alt="Where to find character IDs" />
    </a>
  </div>
</template>

// backend-mode/clients/web/nextjs-iframe/iframe-content/src/components/CharacterList.tsx
import { useState } from 'react'
import { DEFAULT_CHARACTERS } from '../data/characters'

const DASH_URL = 'https://app.spatius.ai'

interface Character {
  id: string
  name: string
}

interface Props {
  loadingId: string | null
  loadProgress: number
  onSelect: (id: string, name: string) => void
}

export default function CharacterList({ loadingId, loadProgress, onSelect }: Props) {
  const [adding, setAdding] = useState(false)
  const [customId, setCustomId] = useState('')
  const [customChars, setCustomChars] = useState<Character[]>([])

  const handleAdd = () => {
    const id = customId.trim()
    if (!id) return
    if ([...DEFAULT_CHARACTERS, ...customChars].some(c => c.id === id)) return
    const name = `Custom (${id.slice(0, 6)}...)`
    setCustomChars(prev => [...prev, { id, name }])
    setCustomId('')
    setAdding(false)
  }

  const allChars = [...DEFAULT_CHARACTERS, ...customChars]

  return (
    <div className="character-list">
      <h3>Characters</h3>
      <div className="character-items">
        {allChars.map(c => (
          <button
            key={c.id}
            className={`character-item ${loadingId === c.id ? 'loading' : ''}`}
            disabled={loadingId !== null}
            onClick={() => onSelect(c.id, c.name)}
          >
            <span className="character-avatar">
              {c.name.charAt(0)}
            </span>
            <span className="character-name">{c.name}</span>
            {loadingId === c.id && <span className="character-progress">{Math.round(loadProgress)}%</span>}
          </button>
        ))}

        {adding ? (
          <div className="custom-id-input">
            <input
              value={customId}
              onChange={e => setCustomId(e.target.value)}
              onKeyDown={e => e.key === 'Enter' && handleAdd()}
              placeholder="Paste character ID"
              autoFocus
            />
            <div className="custom-id-actions">
              <button className="primary" disabled={!customId.trim() || loadingId !== null} onClick={handleAdd}>Add</button>
              <button className="secondary" onClick={() => { setAdding(false); setCustomId('') }}>Cancel</button>
            </div>
          </div>
        ) : (
          <button className="character-item add-btn" onClick={() => setAdding(true)}>
            <span className="character-avatar add-avatar">+</span>
            <span className="character-name">Custom ID</span>
          </button>
        )}
      </div>

      <a className="guide-thumb list-guide" href={DASH_URL} target="_blank" rel="noreferrer">
        <img src="/public-avatar-guide.png" alt="Where to find character IDs" />
      </a>
    </div>
  )
}
