// direct-mode/clients/web/reference/nextjs-iframe/iframe-content/src/components/AvatarCanvas.tsx
import { useRef } from 'react'
import type { AvatarInstance } from '../hooks/useAvatarSDK'

interface Props {
  avatars: AvatarInstance[]
  activeUid: string | null
  onContainerReady: (uid: string, el: HTMLDivElement) => void
}

export default function AvatarCanvas({ avatars, activeUid, onContainerReady }: Props) {
  const containerRefs = useRef<Map<string, HTMLDivElement>>(new Map())

  const gridClass =
    avatars.length <= 1 ? 'grid-1' :
    avatars.length === 2 ? 'grid-2' :
    'grid-4'

  return (
    <div className={`avatar-canvas ${gridClass}`}>
      {avatars.length === 0 && (
        <div className="canvas-empty">
          Select a character to get started
        </div>
      )}
      {avatars.map(a => (
        <div
          key={a.uid}
          className={`canvas-cell ${a.uid === activeUid ? 'active-cell' : ''}`}
        >
          {a.loading && <div className="canvas-loading">Loading...</div>}
          {a.error && <div className="canvas-error">{a.error}</div>}
          <div
            className="canvas-container"
            ref={el => {
              if (el && !containerRefs.current.has(a.uid)) {
                containerRefs.current.set(a.uid, el)
                onContainerReady(a.uid, el)
              }
            }}
          />
        </div>
      ))}
    </div>
  )
}

// backend-mode/clients/web/vue/src/components/AvatarCanvas.vue
<script setup lang="ts">
import { ref } from 'vue'
import type { AvatarInstance } from '../composables/useAvatarSDK'

defineProps<{
  avatars: AvatarInstance[]
  activeUid: string | null
}>()

const emit = defineEmits<{
  containerReady: [uid: string, el: HTMLDivElement]
}>()

const containerRefs = ref<Map<string, HTMLDivElement>>(new Map())

function gridClass(count: number) {
  if (count <= 1) return 'grid-1'
  if (count === 2) return 'grid-2'
  return 'grid-4'
}

function setContainerRef(uid: string, el: HTMLDivElement | null) {
  if (el && !containerRefs.value.has(uid)) {
    containerRefs.value.set(uid, el)
    emit('containerReady', uid, el)
  }
}
</script>

<template>
  <div :class="['avatar-canvas', gridClass(avatars.length)]">
    <div v-if="avatars.length === 0" class="canvas-empty">
      Select a character to get started
    </div>
    <div
      v-for="a in avatars"
      :key="a.uid"
      :class="['canvas-cell', { 'active-cell': a.uid === activeUid }]"
    >
      <div v-if="a.loading" class="canvas-loading">Loading...</div>
      <div v-if="a.error" class="canvas-error">{{ a.error }}</div>
      <div
        class="canvas-container"
        :ref="(el) => setContainerRef(a.uid, el as HTMLDivElement)"
      />
    </div>
  </div>
</template>
