// backend-mode/clients/web/nextjs-direct/components/ControlPanel.tsx
'use client'

import { useState, useRef, useCallback, useEffect } from 'react'
import type { AvatarController } from '@spatius/avatarkit'
import type { AvatarInstance } from '@/hooks/useAvatarSDK'
import { MicrophonePcmCapture } from '@/utils/audioCapture'

interface AvatarSlot {
  uid: string
  index: number
  name: string
}

interface Props {
  activeAvatar: AvatarInstance | null
  activeController: AvatarController | null
  multiMode?: boolean
  avatarSlots?: AvatarSlot[]
  activeUid?: string | null
  onSlotSelect?: (uid: string) => void
}

const BACKEND_MODE_URL = process.env.NEXT_PUBLIC_BACKEND_MODE_WS_URL || 'ws://localhost:8765/ws/agent'
const SAMPLE_RATE = 16000

function base64Decode(b64: string): Uint8Array {
  const bin = atob(b64)
  const bytes = new Uint8Array(bin.length)
  for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i)
  return bytes
}

function bytesToBase64(bytes: Uint8Array): string {
  let binary = ''
  for (const byte of bytes) binary += String.fromCharCode(byte)
  return btoa(binary)
}

export default function ControlPanel({ activeAvatar, activeController, multiMode, avatarSlots, activeUid, onSlotSelect }: Props) {
  const [backendConnected, setHostConnected] = useState(false)
  const [backendConnecting, setHostConnecting] = useState(false)
  const [backendMicActive, setHostMicActive] = useState(false)
  const [backendTextInput, setHostTextInput] = useState('')
  const hostWsRef = useRef<WebSocket | null>(null)
  const backendTurnMapRef = useRef(new Map<string, string>())
  const microphoneRef = useRef<MicrophonePcmCapture | null>(null)
  // Refs to track latest values inside WS callbacks
  const activeControllerRef = useRef(activeController)
  const activeAvatarRef = useRef(activeAvatar)
  const backendConnectedRef = useRef(false)

  const hasAvatar = activeAvatar?.view !== null && !activeAvatar?.loading

  // Keep refs in sync
  useEffect(() => { activeControllerRef.current = activeController }, [activeController])
  useEffect(() => { activeAvatarRef.current = activeAvatar }, [activeAvatar])
  useEffect(() => { backendConnectedRef.current = backendConnected }, [backendConnected])

  // ========== Backend Mode ==========

  const handleHostMessage = useCallback((msg: any) => {
    const ctrl = activeControllerRef.current
    const type = msg.type
    if (type === 'ready') {
      setHostConnected(true)
      setHostConnecting(false)
      backendConnectedRef.current = true
      const avatarId = activeAvatarRef.current?.characterId || ''
      hostWsRef.current?.send(JSON.stringify({ type: 'set_avatar', avatarId }))
    } else if (type === 'avatar_audio') {
      const audioB64 = msg.audio || ''
      const turnId = msg.turnId
      const isLast = msg.isLast ?? false
      const audioBytes = audioB64 ? base64Decode(audioB64) : new Uint8Array(0)
      const localCid = ctrl?.yieldAudioData(audioBytes, isLast)
      if (localCid && !backendTurnMapRef.current.has(turnId)) {
        backendTurnMapRef.current.set(turnId, localCid)
      }
    } else if (type === 'avatar_frames') {
      const frames = (msg.frames || []).map((b64: string) => base64Decode(b64))
      const localCid = backendTurnMapRef.current.get(msg.turnId)
      if (localCid && frames.length) {
        ctrl?.yieldFramesData(frames, localCid)
      }
      if (msg.isLast) {
        backendTurnMapRef.current.delete(msg.turnId)
      }
    } else if (type === 'interrupt') {
      ctrl?.interrupt()
      backendTurnMapRef.current.clear()
    } else if (type === 'error') {
      console.error('Host server error:', msg.message)
    }
  }, [])

  const backendConnect = useCallback(async () => {
    if (hostWsRef.current || backendConnecting) return
    setHostConnecting(true)
    try {
      await activeControllerRef.current?.initializeAudioContext()
    } catch (e) {
      console.error('Audio context init failed:', e)
      setHostConnecting(false)
      return
    }

    const ws = new WebSocket(BACKEND_MODE_URL)
    hostWsRef.current = ws

    ws.onmessage = (event) => {
      let msg: any
      try { msg = JSON.parse(event.data) } catch { return }
      handleHostMessage(msg)
    }
    ws.onerror = () => {
      console.error('Host server connection failed')
      setHostConnecting(false)
      setHostConnected(false)
      backendConnectedRef.current = false
    }
    ws.onclose = () => {
      hostWsRef.current = null
      setHostConnected(false)
      setHostConnecting(false)
      setHostMicActive(false)
      backendConnectedRef.current = false
    }
  }, [backendConnecting, handleHostMessage])

  const backendDisconnect = useCallback(() => {
    if (microphoneRef.current) {
      microphoneRef.current.stop()
      microphoneRef.current = null
      setHostMicActive(false)
    }
    if (hostWsRef.current) {
      hostWsRef.current.close()
      hostWsRef.current = null
    }
    setHostConnected(false)
    backendConnectedRef.current = false
    backendTurnMapRef.current.clear()
  }, [])

  const toggleMic = useCallback(async () => {
    if (backendMicActive) {
      // Stop mic
      if (microphoneRef.current) {
        await microphoneRef.current.stop()
        microphoneRef.current = null
      }
      setHostMicActive(false)
      if (hostWsRef.current?.readyState === WebSocket.OPEN) {
        hostWsRef.current.send(JSON.stringify({ type: 'mic_end' }))
      }
    } else {
      // Start mic — auto-connect if needed
      if (!backendConnectedRef.current) {
        await backendConnect()
        // Wait for ready
        await new Promise<void>((resolve) => {
          const check = setInterval(() => {
            if (backendConnectedRef.current) { clearInterval(check); resolve() }
          }, 100)
          setTimeout(() => { clearInterval(check); resolve() }, 3000)
        })
      }
      if (!backendConnectedRef.current) return
      const mic = new MicrophonePcmCapture(SAMPLE_RATE)
      microphoneRef.current = mic
      await mic.start((chunk: Uint8Array) => {
        if (hostWsRef.current?.readyState === WebSocket.OPEN) {
          hostWsRef.current.send(JSON.stringify({ type: 'mic_audio', audio: bytesToBase64(chunk) }))
        }
      })
      setHostMicActive(true)
    }
  }, [backendMicActive, backendConnect])

  const sendTextQuery = useCallback(async () => {
    const text = backendTextInput.trim()
    if (!text) return
    if (!backendConnectedRef.current) {
      await backendConnect()
      await new Promise<void>((resolve) => {
        const check = setInterval(() => {
          if (backendConnectedRef.current) { clearInterval(check); resolve() }
        }, 100)
        setTimeout(() => { clearInterval(check); resolve() }, 3000)
      })
    }
    if (hostWsRef.current?.readyState === WebSocket.OPEN) {
      hostWsRef.current.send(JSON.stringify({ type: 'text_query', text }))
      setHostTextInput('')
    }
  }, [backendTextInput, backendConnect])

  const [paused, setPaused] = useState(false)

  const handleTogglePause = () => {
    if (paused) {
      activeController?.resume()
    } else {
      activeController?.pause()
    }
    setPaused(!paused)
  }
  const handleInterrupt = () => {
    activeController?.interrupt()
    if (microphoneRef.current) { microphoneRef.current.stop(); microphoneRef.current = null; setHostMicActive(false) }
    if (hostWsRef.current?.readyState === WebSocket.OPEN) {
      hostWsRef.current.send(JSON.stringify({ type: 'interrupt' }))
    }
    backendTurnMapRef.current.clear()
  }

  // Cleanup on unmount
  useEffect(() => {
    return () => {
      if (microphoneRef.current) { microphoneRef.current.stop(); microphoneRef.current = null }
      if (hostWsRef.current) { hostWsRef.current.close(); hostWsRef.current = null }
    }
  }, [])

  return (
    <div className="control-panel">
      <h3>Controls</h3>
      {activeAvatar && (
        <div className="status-bar">
          <div className="status-row">
            <span className="status-label">Server</span>
            <span className="status-value">
              {backendConnected ? 'connected' : backendConnecting ? 'connecting...' : 'disconnected'}
            </span>
          </div>
          <div className="status-row">
            <span className="status-label">Conversation</span>
            <span className="status-value">{activeAvatar.conversationState}</span>
          </div>
          {activeAvatar.error && (
            <div className="status-row error">
              <span className="status-label">Error</span>
              <span className="status-value error-text">{activeAvatar.error}</span>
            </div>
          )}
        </div>
      )}
      {multiMode && avatarSlots && avatarSlots.length > 0 && (
        <div className="slot-selector">
          <h4>Active Avatar</h4>
          <div className="slot-list">
            {avatarSlots.map(s => (
              <button key={s.uid} className={`slot-btn ${s.uid === activeUid ? 'active' : ''}`} onClick={() => onSlotSelect?.(s.uid)}>
                <span className="slot-index">{s.index}</span>
                <span className="slot-name">{s.name}</span>
              </button>
            ))}
          </div>
        </div>
      )}
      {!hasAvatar && <p className="panel-hint">Load a character first</p>}
      {hasAvatar && (
        <>
          <div className="btn-row" style={{ marginBottom: 8 }}>
            {!backendConnected ? (
              <button className="primary" disabled={backendConnecting} onClick={backendConnect}>
                {backendConnecting ? 'Connecting...' : 'Connect'}
              </button>
            ) : (
              <button className="secondary" onClick={backendDisconnect}>
                Disconnect
              </button>
            )}
          </div>

          <button
            className={`full-width ${backendMicActive ? 'danger' : 'primary'}`}
            disabled={!hasAvatar}
            onClick={toggleMic}
          >
            {backendMicActive ? 'Stop Mic' : 'Start Mic'}
          </button>

          <form className="host-text-form" onSubmit={(e) => { e.preventDefault(); sendTextQuery() }} style={{ marginTop: 8 }}>
            <input
              type="text"
              placeholder="Type a message..."
              className="host-text-input"
              disabled={!hasAvatar}
              value={backendTextInput}
              onChange={(e) => setHostTextInput(e.target.value)}
            />
            <button type="submit" className="primary" disabled={!backendTextInput.trim() || !hasAvatar}>
              Send
            </button>
          </form>

          <p className="host-hint">
            Connects to <code>{BACKEND_MODE_URL}</code>.
            Using Backend Mode server — see <a href="https://github.com/spatius-ai/spatius-avatar-demo" target="_blank" rel="noreferrer">github.com/spatius-ai/spatius-avatar-demo</a>.
          </p>
        </>
      )}
      {hasAvatar && (
        <div className="btn-row">
          <button className="secondary" onClick={handleTogglePause}>{paused ? 'Resume' : 'Pause'}</button>
          <button className="danger" onClick={handleInterrupt}>Interrupt</button>
        </div>
      )}
    </div>
  )
}

// backend-mode/clients/web/vue/src/components/ControlPanel.vue
<script setup lang="ts">
import { ref, computed, onUnmounted } from 'vue'
import type { AvatarController } from '@spatius/avatarkit'
import type { AvatarInstance } from '../composables/useAvatarSDK'
import { MicrophonePcmCapture } from '../utils/audioCapture'

interface AvatarSlot {
  uid: string
  index: number
  name: string
}

const props = defineProps<{
  activeAvatar: AvatarInstance | null
  activeController: AvatarController | null
  multiMode?: boolean
  avatarSlots?: AvatarSlot[]
  activeUid?: string | null
}>()

const emit = defineEmits<{
  slotSelect: [uid: string]
}>()

const BACKEND_MODE_URL = import.meta.env.VITE_BACKEND_MODE_WS_URL || 'ws://localhost:8765/ws/agent'
const SAMPLE_RATE = 16000

// Backend Mode state
const hostWs = ref<WebSocket | null>(null)
const backendConnected = ref(false)
const backendConnecting = ref(false)
const backendMicActive = ref(false)
const backendTextInput = ref('')
const backendTurnMap = new Map<string, string>()
let microphone: MicrophonePcmCapture | null = null

const hasAvatar = computed(() => props.activeAvatar?.view !== null && !props.activeAvatar?.loading)

function base64Decode(b64: string): Uint8Array {
  const bin = atob(b64)
  const bytes = new Uint8Array(bin.length)
  for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i)
  return bytes
}

function bytesToBase64(bytes: Uint8Array): string {
  let binary = ''
  for (const byte of bytes) binary += String.fromCharCode(byte)
  return btoa(binary)
}

function handleHostMessage(msg: any) {
  const type = msg.type
  if (type === 'ready') {
    backendConnected.value = true
    backendConnecting.value = false
    const avatarId = props.activeAvatar?.characterId || ''
    hostWs.value?.send(JSON.stringify({ type: 'set_avatar', avatarId }))
  } else if (type === 'avatar_audio') {
    const audioB64 = msg.audio || ''
    const turnId = msg.turnId
    const isLast = msg.isLast ?? false
    const audioBytes = audioB64 ? base64Decode(audioB64) : new Uint8Array(0)
    const localCid = props.activeController?.yieldAudioData(audioBytes, isLast)
    if (localCid && !backendTurnMap.has(turnId)) {
      backendTurnMap.set(turnId, localCid)
    }
  } else if (type === 'avatar_frames') {
    const frames = (msg.frames || []).map((b64: string) => base64Decode(b64))
    const localCid = backendTurnMap.get(msg.turnId)
    if (localCid && frames.length) {
      props.activeController?.yieldFramesData(frames, localCid)
    }
    if (msg.isLast) {
      backendTurnMap.delete(msg.turnId)
    }
  } else if (type === 'interrupt') {
    props.activeController?.interrupt()
    backendTurnMap.clear()
  } else if (type === 'error') {
    console.error('Host server error:', msg.message)
  }
}

async function backendConnect() {
  if (hostWs.value || backendConnecting.value) return
  backendConnecting.value = true
  try {
    await props.activeController?.initializeAudioContext()
  } catch (e) {
    console.error('Audio context init failed:', e)
    backendConnecting.value = false
    return
  }

  const ws = new WebSocket(BACKEND_MODE_URL)
  hostWs.value = ws

  ws.onmessage = (event) => {
    let msg: any
    try { msg = JSON.parse(event.data) } catch { return }
    handleHostMessage(msg)
  }
  ws.onerror = () => {
    console.error('Host server connection failed')
    backendConnecting.value = false
    backendConnected.value = false
  }
  ws.onclose = () => {
    hostWs.value = null
    backendConnected.value = false
    backendConnecting.value = false
    backendMicActive.value = false
  }
}

function backendDisconnect() {
  if (microphone) { microphone.stop(); microphone = null; backendMicActive.value = false }
  if (hostWs.value) { hostWs.value.close(); hostWs.value = null }
  backendConnected.value = false
  backendTurnMap.clear()
}

async function toggleMic() {
  if (backendMicActive.value) {
    // Stop mic
    if (microphone) { await microphone.stop(); microphone = null }
    backendMicActive.value = false
    if (hostWs.value?.readyState === WebSocket.OPEN) {
      hostWs.value.send(JSON.stringify({ type: 'mic_end' }))
    }
  } else {
    // Start mic — auto-connect if needed
    if (!backendConnected.value) {
      await backendConnect()
      // Wait for ready
      await new Promise<void>((resolve) => {
        const check = setInterval(() => {
          if (backendConnected.value) { clearInterval(check); resolve() }
        }, 100)
        setTimeout(() => { clearInterval(check); resolve() }, 3000)
      })
    }
    if (!backendConnected.value) return
    microphone = new MicrophonePcmCapture(SAMPLE_RATE)
    await microphone.start((chunk: Uint8Array) => {
      if (hostWs.value?.readyState === WebSocket.OPEN) {
        hostWs.value.send(JSON.stringify({ type: 'mic_audio', audio: bytesToBase64(chunk) }))
      }
    })
    backendMicActive.value = true
  }
}

async function sendTextQuery() {
  const text = backendTextInput.value.trim()
  if (!text) return
  if (!backendConnected.value) {
    await backendConnect()
    await new Promise<void>((resolve) => {
      const check = setInterval(() => {
        if (backendConnected.value) { clearInterval(check); resolve() }
      }, 100)
      setTimeout(() => { clearInterval(check); resolve() }, 3000)
    })
  }
  if (hostWs.value?.readyState === WebSocket.OPEN) {
    hostWs.value.send(JSON.stringify({ type: 'text_query', text }))
    backendTextInput.value = ''
  }
}

const paused = ref(false)

function handlePauseResume() {
  if (paused.value) {
    props.activeController?.resume()
  } else {
    props.activeController?.pause()
  }
  paused.value = !paused.value
}

function handleInterrupt() {
  props.activeController?.interrupt()
  if (microphone) { microphone.stop(); microphone = null; backendMicActive.value = false }
  if (hostWs.value?.readyState === WebSocket.OPEN) {
    hostWs.value.send(JSON.stringify({ type: 'interrupt' }))
  }
  backendTurnMap.clear()
}

onUnmounted(() => {
  backendDisconnect()
})
</script>

<template>
  <div class="control-panel">
    <h3>Controls</h3>
    <!-- Status -->
    <div v-if="activeAvatar" class="status-bar">
      <div class="status-row">
        <span class="status-label">Server</span>
        <span class="status-value">{{ backendConnected ? 'connected' : backendConnecting ? 'connecting...' : 'disconnected' }}</span>
      </div>
      <div class="status-row">
        <span class="status-label">Conversation</span>
        <span class="status-value">{{ activeAvatar.conversationState }}</span>
      </div>
      <div v-if="activeAvatar.error" class="status-row error">
        <span class="status-label">Error</span>
        <span class="status-value error-text">{{ activeAvatar.error }}</span>
      </div>
    </div>

    <!-- Slot selector in multi mode -->
    <div v-if="multiMode && avatarSlots && avatarSlots.length > 0" class="slot-selector">
      <h4>Active Avatar</h4>
      <div class="slot-list">
        <button
          v-for="s in avatarSlots"
          :key="s.uid"
          :class="['slot-btn', { active: s.uid === activeUid }]"
          @click="emit('slotSelect', s.uid)"
        >
          <span class="slot-index">{{ s.index }}</span>
          <span class="slot-name">{{ s.name }}</span>
        </button>
      </div>
    </div>

    <p v-if="!hasAvatar" class="panel-hint">Load a character first</p>

    <!-- Backend Mode -->
    <template v-if="hasAvatar">
      <div class="btn-row" style="margin-bottom: 8px;">
        <button
          v-if="!backendConnected"
          class="primary"
          :disabled="backendConnecting"
          @click="backendConnect"
        >
          {{ backendConnecting ? 'Connecting...' : 'Connect' }}
        </button>
        <button
          v-else
          class="secondary"
          @click="backendDisconnect"
        >
          Disconnect
        </button>
      </div>

      <button
        :class="['full-width', backendMicActive ? 'danger' : 'primary']"
        :disabled="!hasAvatar"
        @click="toggleMic"
      >
        {{ backendMicActive ? 'Stop Mic' : 'Start Mic' }}
      </button>

      <form class="host-text-form" @submit.prevent="sendTextQuery" style="margin-top: 8px;">
        <input
          v-model="backendTextInput"
          type="text"
          placeholder="Type a message..."
          class="host-text-input"
          :disabled="!hasAvatar"
        />
        <button type="submit" class="primary" :disabled="!backendTextInput.trim() || !hasAvatar">
          Send
        </button>
      </form>

      <p class="host-hint">
        Connects to <code>{{ BACKEND_MODE_URL }}</code>.
        Using Backend Mode server — see <a href="https://github.com/spatius-ai/spatius-avatar-demo" target="_blank">github.com/spatius-ai/spatius-avatar-demo</a>.
      </p>
    </template>

    <!-- Common controls -->
    <div v-if="hasAvatar" class="btn-row">
      <button class="secondary" @click="handlePauseResume">{{ paused ? 'Resume' : 'Pause' }}</button>
      <button class="danger" @click="handleInterrupt">Interrupt</button>
    </div>
  </div>
</template>
